### PR TITLE
Medio

### PR DESCRIPTION
**Pull request by gnugat**
This Pull Request introduces the usage of [Medio](http://gnugat.github.io/medio/) a third party Code Generator library, as discussed in #11 .

Technically, it introduces a `ArgumentsGenerator` class which takes care of generating the arguments (using Medio).
Concretely, it will put each arguments on their own line if the inline alternative would have been longer than 120 characters.

Medio provides some Model classes that represents the code, and uses [Twig templates](http://twig.sensiolabs.org/) to actually generate the corresponding code. It provides a default set, but they can be overrided.
Medio uses [Puli](http://docs.puli.io/en/latest/) to make the default templates available without having to hardcode paths.

Currently in version 1.0.0-alpha3, Medio will progressively get more features (like PHPdoc and use statements), so this extension can benefit from them.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Honestly I found this approach a bit weird. Mainly becauseof the Twig templating engine. IMO an AST builder would be better here (although it is more complex), but there is no need for such templating and pure PHP (some would argue with this whether Twig is PHP or not, but it is NOT, it is just parsed to PHP code).

Also, an AST builder already has all the necessary features that PHP possibly can have, since it is using PHP token parser to parse or build PHP code.

https://github.com/nikic/PHP-Parser

**Comment by gnugat** [comment]
I find it more handy to build models to represent a file structure (a Class, its Properties, its constants and its Methods), and then to use templates to transform it into code as it allows easy customizations.

PHP Parser is a great tool, and I intend to use it to build models from existing source code. But when it comes to pretty printing, it's kind of hard to customize the generated code (see this attempt to make it PSR 2 compliant: https://github.com/tcopestake/PHP-Parser-PSR-2-pretty-printer).
Changing the coding style of the outputed code shouldn't involve new classes and PHP code, to me it is the responsibility of templates.

I'm glad you've brought the topic though :) .

**Comment by sagikazarmark** [comment]
The way you build your syntax tree is absolutely up to you. Using models is one way. An interesting solution is created by @Ocramius using visitor pattern.

https://github.com/Ocramius/CodeGenerationUtils

About PSR2 compliance: I cannot really say anything as I only generated temporary classes so far, didn't care about CS.

About using templates, my concern are:

* It adds too much external dependencies to the generation process (engine, templates anything related to those)
* The only extension point is the template itself
* The knowledge cannot be overridden in pure PHP since only some data is stored in PHP (which is not true in case of AST)
* Overriding templates can be a big hassle: locate templates from various paths, hard to configure (which is - again - not an issue in case of AST)

These are only a few things I can quickly think of and I am sure there are more issues to face with. The problem is that it adds a relatively big architecture to the whole process (configuration, responsibilities, etc.) so there are a lot of points where this approach fails IMO.

**Comment by gnugat** [comment]
I get your point, and it is especially true when it comes to full code generation (e.g. generate code in method body).
On the other hand, phpspec already relies on (home made) templates. While it avoids the issue of adding external dependencies, it has the drawback of being quite limited...

I really feel there's some improvements to be done here, the code generation logic should be extracted from phpspec and put in its own library. I've tried to provide one implementation for this, but as you suggest there's many other ways to do it.

**Comment by gnugat** [comment]
Actually, this PR is a bit obsolete: Medio has been renamed, put in its own organization and split into smaller packages since. It isn't coupled anymore to Twig: we can provide our own `TemplateEngine` and templates (but for now the only package available for this is TwigTemplateEngine).

I didn't get much feedback from @ciaranmcnulty on this issue anyway, so I'll just close it for now :) .

**Comment by sagikazarmark** [comment]
Yeah, I am aware of the rename. I agree with you, code generation should be extracted.

The other issue is that medio is a fully featured generation library, while this is only an extension. However IMO this feature should be in the core repository (even if as an extension or an optional thing)

**Comment by gnugat** [comment]
I'm not sure what you mean: should I create a phpspec extension in Medio's organization?

**Comment by sagikazarmark** [comment]
No, I meant phpspec should have it's code generation extracted to a separate package and type-hinted methods should be in the core.

This way you could write your own code generation extension for phpspec replacing the original, since it would provide an interface.

**Comment by gnugat** [comment]
Ha I see. Yes, I agree with you :) .
But currently it generates a typehint based on the provided mock, which can be either an interface or an implementation. phpspec philosophy would be to promote typehint against interfaces, which explains why it isn't in the core, yet.

**Pull request closed without merging**
