### PR TITLE
phpspec 5.0 support

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
travis green

**Comment by ciaranmcnulty** [comment]
Thanks for doing this so quickly! I wonder if we should create a new major version if bumping the PHP?

**Comment by samsonasik** [comment]
I think major version is fine as previous versions using major versions for update phpspec major versions. We not only bumping php requirement, but update the code signature ( void declaration at ::generate()).

**Comment by msvrtan** [comment]
I just saw phpspec 5.0 is out but I'm blocked to upgrade by this extension :( Any chance of this getting in and publishing new release?

**Comment by ciaranmcnulty** [comment]
Made a release, thanks @samsonasik

**Comment by msvrtan** [comment]
Wow, that was quick! Thank you Ciaran!

**Pull request merged**
